CREATE TABLE TON(
	MaVT VARCHAR(4) PRIMARY KEY NOT NULL,
	TenVT NVARCHAR(30),
	SoLuongT INT
);

CREATE TABLE NHAP(
	SoHDN VARCHAR(4) PRIMARY KEY NOT NULL,
	MaVT VARCHAR(4) FOREIGN KEY REFERENCES TON(MaVT),
	SoLuongN INT,
	DonGiaN MONEY,
	NgayN DATE
);

CREATE TABLE XUAT(
	SoHDX VARCHAR(4) PRIMARY KEY NOT NULL,
	MaVT VARCHAR(4) FOREIGN KEY REFERENCES TON(MaVT),
	SoLuongX INT,
	DonGiaX MONEY,
	NgayX DATE
);

INSERT INTO TON VALUES('VT01', N'Gạch ống', 255), ('VT02', N'Ngói đỏ', 137), ('VT03', N'Gạch men lát tường', 300),
('VT04', N'Đá hoa cương', 435), ('VT05', N'Xi măng', 567)

INSERT INTO NHAP VALUES('N001', 'VT01', 500, 11700000, '2019-03-27'), ('N002', 'VT04', 600, 18500000, '2020-05-27'),
('N003', 'VT02', 337, 17000000, '2020-12-27')

INSERT INTO XUAT VALUES('X001', 'VT01', 245, 5890000, '2019-03-28'), ('X002', 'VT03', 200, 11200000, '2020-05-29')

go
-- cau2
CREATE VIEW CAU2 AS
SELECT TON.MaVT,TenVT, SUM(SoLuongX*DonGiaX) AS 'TIEN BAN'
FROM xuat inner join ton on xuat.mavt=ton.mavt
group by ton.mavt,tenvt 

--TEST
SELECT * FROM CAU2

---CAU 3
CREATE VIEW CAU3
AS
select TON.TenVT, sum(SoLuongX) as 'TONG SL'
from XUAT inner join TON on XUAT.MaVT=TON.MaVT
group by TON.TenVT

SELECT * FROM CAU3
-- CAU 4
CREATE VIEW CAU4
AS
select TON.TenVT, sum(SoLuongN) as 'TONG SL'
from NHAP inner join TON on NHAP.MaVT=TON.MaVT
group by TON.TenVT

SELECT * FROM CAU4
-- cau5
CREATE VIEW CAU5 AS
select TON.MaVT,TON.TenVT,sum(SoLuongN)-sum(SoLuongX) +
sum(SoLuongT) as TONGTON
from NHAP inner join ton on NHAP.MaVT=TON.MaVT
inner join XUAT on TON.MaVT=XUAT.MaVT
group by TON.MaVT,TON.TenVT

SELECT * FROM CAU5
-- Cau6
CREATE VIEW CAU6 AS
select TenVT
from TON
where SoLuongT = (select max(SoLuongT) from TON)
SELECT * FROM CAU6

-- CAU7
CREATE VIEW CAU7
AS
select TON.MaVT,TON.TenVT
from TON inner join XUAT on TON.MaVT=XUAT.MaVT
group by TON.MaVT,TON.TenVT
having sum(SoLuongX)>=100

SELECT * FROM CAU7
--CAU 8
CREATE VIEW CAU8
AS
SELECT MONTH(XUAT.NgayX) AS N'THANG XUAT',YEAR(XUAT.NgayX) AS N'NAM XUAT', SUM(SoLuongX) AS N'SO LUONG XUAT'
FROM XUAT
GROUP BY XUAT.NgayX
SELECT * FROM CAU8

--CAU 9
CREATE VIEW CAU9
AS
SELECT TON.MaVT,TON.TenVT,NHAP.SoLuongN,XUAT.SoLuongX,NHAP.DonGiaN,XUAT.DonGiaX,NHAP.NgayN,XUAT.NgayX
FROM TON INNER JOIN NHAP ON TON.MaVT=NHAP.MaVT INNER JOIN XUAT ON TON.MaVT=XUAT.MaVT
GROUP BY TON.MaVT,TON.TenVT,NHAP.SoLuongN,XUAT.SoLuongX,NHAP.DonGiaN,XUAT.DonGiaX,NHAP.NgayN,XUAT.NgayX

SELECT * FROM CAU9
